/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.apis

import com.rizalanggoro.presensigo.openapi.models.CreateGeneralAttendanceRecordStudentReq
import com.rizalanggoro.presensigo.openapi.models.CreateGeneralAttendanceReq
import com.rizalanggoro.presensigo.openapi.models.CreateSubjectAttendanceRecordReq
import com.rizalanggoro.presensigo.openapi.models.CreateSubjectAttendanceRecordStudentReq
import com.rizalanggoro.presensigo.openapi.models.CreateSubjectAttendanceReq
import com.rizalanggoro.presensigo.openapi.models.GetAllSubjectAttendancesRes
import com.rizalanggoro.presensigo.openapi.models.GetSubjectAttendanceRes
import com.rizalanggoro.presensigo.openapi.models.RequestsUpdateGeneralAttendance
import com.rizalanggoro.presensigo.openapi.models.ResponsesCreateGeneralAttendance
import com.rizalanggoro.presensigo.openapi.models.ResponsesCreateGeneralAttendanceRecordStudent
import com.rizalanggoro.presensigo.openapi.models.ResponsesCreateSubjectAttendance
import com.rizalanggoro.presensigo.openapi.models.ResponsesCreateSubjectAttendanceRecord
import com.rizalanggoro.presensigo.openapi.models.ResponsesCreateSubjectAttendanceRecordStudent
import com.rizalanggoro.presensigo.openapi.models.ResponsesDeleteGeneralAttendance
import com.rizalanggoro.presensigo.openapi.models.ResponsesDeleteSubjectAttendanceRecord
import com.rizalanggoro.presensigo.openapi.models.ResponsesGetAllGeneralAttendanceRecords
import com.rizalanggoro.presensigo.openapi.models.ResponsesGetAllGeneralAttendances
import com.rizalanggoro.presensigo.openapi.models.ResponsesGetAllSubjectAttendanceRecords
import com.rizalanggoro.presensigo.openapi.models.ResponsesGetGeneralAttendance
import com.rizalanggoro.presensigo.openapi.models.ResponsesUpdateGeneralAttendance

import com.rizalanggoro.presensigo.openapi.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import java.text.DateFormat

    open class AttendanceApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    jsonBlock: GsonBuilder.() -> Unit = ApiClient.JSON_DEFAULT,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
        jsonBlock,
    ) {

        /**
        * POST /api/v1/general-attendances
        * 
        * 
         * @param body body 
         * @return ResponsesCreateGeneralAttendance
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createGeneralAttendance(body: CreateGeneralAttendanceReq): HttpResponse<ResponsesCreateGeneralAttendance> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/general-attendances",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/general-attendances/records/student
        * 
        * 
         * @param body body 
         * @return ResponsesCreateGeneralAttendanceRecordStudent
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createGeneralAttendanceRecordStudent(body: CreateGeneralAttendanceRecordStudentReq): HttpResponse<ResponsesCreateGeneralAttendanceRecordStudent> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/general-attendances/records/student",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @param body body 
         * @return ResponsesCreateSubjectAttendance
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createSubjectAttendance(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int, body: CreateSubjectAttendanceReq): HttpResponse<ResponsesCreateSubjectAttendance> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @param subjectAttendanceId subject attendance id 
         * @param body body 
         * @return ResponsesCreateSubjectAttendanceRecord
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createSubjectAttendanceRecord(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int, subjectAttendanceId: kotlin.Int, body: CreateSubjectAttendanceRecordReq): HttpResponse<ResponsesCreateSubjectAttendanceRecord> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId").replace("{" + "subject_attendance_id" + "}", "$subjectAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /api/v1/subject-attendances/records/student
        * 
        * 
         * @param body body 
         * @return ResponsesCreateSubjectAttendanceRecordStudent
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun createSubjectAttendanceRecordStudent(body: CreateSubjectAttendanceRecordStudentReq): HttpResponse<ResponsesCreateSubjectAttendanceRecordStudent> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/subject-attendances/records/student",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /api/v1/general-attendances/{general_attendance_id}
        * 
        * 
         * @param generalAttendanceId general attendance id 
         * @return ResponsesDeleteGeneralAttendance
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun deleteGeneralAttendance(generalAttendanceId: kotlin.Int): HttpResponse<ResponsesDeleteGeneralAttendance> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/general-attendances/{general_attendance_id}".replace("{" + "general_attendance_id" + "}", "$generalAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records/{record_id}
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @param subjectAttendanceId subject attendance id 
         * @param recordId record id 
         * @return ResponsesDeleteSubjectAttendanceRecord
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun deleteSubjectAttendanceRecord(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int, subjectAttendanceId: kotlin.Int, recordId: kotlin.Int): HttpResponse<ResponsesDeleteSubjectAttendanceRecord> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records/{record_id}".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId").replace("{" + "subject_attendance_id" + "}", "$subjectAttendanceId").replace("{" + "record_id" + "}", "$recordId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/general-attendances/{general_attendance_id}/records
        * 
        * 
         * @param generalAttendanceId general attendance id 
         * @return ResponsesGetAllGeneralAttendanceRecords
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllGeneralAttendanceRecords(generalAttendanceId: kotlin.Int): HttpResponse<ResponsesGetAllGeneralAttendanceRecords> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/general-attendances/{general_attendance_id}/records".replace("{" + "general_attendance_id" + "}", "$generalAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/general-attendances
        * 
        * 
         * @return ResponsesGetAllGeneralAttendances
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllGeneralAttendances(): HttpResponse<ResponsesGetAllGeneralAttendances> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/general-attendances",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @param subjectAttendanceId subject attendance id 
         * @return ResponsesGetAllSubjectAttendanceRecords
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllSubjectAttendanceRecords(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int, subjectAttendanceId: kotlin.Int): HttpResponse<ResponsesGetAllSubjectAttendanceRecords> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}/records".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId").replace("{" + "subject_attendance_id" + "}", "$subjectAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @return GetAllSubjectAttendancesRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getAllSubjectAttendances(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int): HttpResponse<GetAllSubjectAttendancesRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/general-attendances/{general_attendance_id}
        * 
        * 
         * @param generalAttendanceId general attendance id 
         * @return ResponsesGetGeneralAttendance
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getGeneralAttendance(generalAttendanceId: kotlin.Int): HttpResponse<ResponsesGetGeneralAttendance> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/general-attendances/{general_attendance_id}".replace("{" + "general_attendance_id" + "}", "$generalAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}
        * 
        * 
         * @param batchId batch id 
         * @param majorId major id 
         * @param classroomId classroom id 
         * @param subjectAttendanceId subject attendance id 
         * @return GetSubjectAttendanceRes
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun getSubjectAttendance(batchId: kotlin.Int, majorId: kotlin.Int, classroomId: kotlin.Int, subjectAttendanceId: kotlin.Int): HttpResponse<GetSubjectAttendanceRes> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}".replace("{" + "batch_id" + "}", "$batchId").replace("{" + "major_id" + "}", "$majorId").replace("{" + "classroom_id" + "}", "$classroomId").replace("{" + "subject_attendance_id" + "}", "$subjectAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * PUT /api/v1/general_attendances/{general_attendance_id}
        * 
        * 
         * @param generalAttendanceId general attendance id 
         * @param body body 
         * @return ResponsesUpdateGeneralAttendance
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun updateGeneralAttendance(generalAttendanceId: kotlin.Int, body: RequestsUpdateGeneralAttendance): HttpResponse<ResponsesUpdateGeneralAttendance> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/v1/general_attendances/{general_attendance_id}".replace("{" + "general_attendance_id" + "}", "$generalAttendanceId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
