/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param batchId 
 * @param name 
 */


data class ApiInternalFeaturesMajorDtoRequestsUpdate (

    @SerializedName("batch_id")
    val batchId: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.String

) {


}

