/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param token 
 */


data class AuthLoginResponse (

    @SerializedName("access_token")
    val accessToken: kotlin.String? = null,

    @SerializedName("token")
    val token: kotlin.String? = null

) {


}

