/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DtoClassroom
import com.rizalanggoro.presensigo.openapi.models.DtoMajor
import com.rizalanggoro.presensigo.openapi.models.DtoStudent

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param classroom 
 * @param major 
 * @param student 
 */


data class CombinedStudentMajorClassroom (

    @SerializedName("classroom")
    val classroom: DtoClassroom,

    @SerializedName("major")
    val major: DtoMajor,

    @SerializedName("student")
    val student: DtoStudent

) {


}

