/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: AttendanceStatusTypePresentOnTime,AttendanceStatusTypePresentLate,AttendanceStatusTypeSick,AttendanceStatusTypePermission,AttendanceStatusTypeAlpha
 */

enum class ConstantsAttendanceStatusType(val value: kotlin.String) {

    @SerializedName(value = "present-on-time")
    AttendanceStatusTypePresentOnTime("present-on-time"),

    @SerializedName(value = "present-late")
    AttendanceStatusTypePresentLate("present-late"),

    @SerializedName(value = "sick")
    AttendanceStatusTypeSick("sick"),

    @SerializedName(value = "permission")
    AttendanceStatusTypePermission("permission"),

    @SerializedName(value = "alpha")
    AttendanceStatusTypeAlpha("alpha");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConstantsAttendanceStatusType) "$data" else null

        /**
         * Returns a valid [ConstantsAttendanceStatusType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConstantsAttendanceStatusType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

