/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.ModelsAttendanceStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param note 
 * @param status 
 * @param studentId 
 */


data class CreateAttendanceItemReq (

    @SerializedName("note")
    val note: kotlin.String? = null,

    @SerializedName("status")
    val status: ModelsAttendanceStatus? = null,

    @SerializedName("student_id")
    val studentId: kotlin.Int? = null

) {


}

