/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.CreateAttendanceItemReq

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attendanceStudents 
 * @param classroomId 
 * @param date 
 */


data class CreateAttendanceReq (

    @SerializedName("attendance_students")
    val attendanceStudents: kotlin.collections.List<CreateAttendanceItemReq>? = null,

    @SerializedName("classroom_id")
    val classroomId: kotlin.Int? = null,

    @SerializedName("date")
    val date: kotlin.String? = null

) {


}

