/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.ConstantsAttendanceStatusType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status 
 * @param studentId 
 */


data class CreateSubjectAttendanceRecordReq (

    @SerializedName("status")
    val status: ConstantsAttendanceStatusType,

    @SerializedName("student_id")
    val studentId: kotlin.Int

) {


}

