/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code 
 * @param datetime 
 * @param id 
 * @param note 
 * @param schoolId 
 */


data class DomainsGeneralAttendance (

    @SerializedName("code")
    val code: kotlin.String,

    @SerializedName("datetime")
    val datetime: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("note")
    val note: kotlin.String,

    @SerializedName("school_id")
    val schoolId: kotlin.Int

) {


}

