/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Classroom
import com.rizalanggoro.presensigo.openapi.models.DomainsStudent
import com.rizalanggoro.presensigo.openapi.models.Major

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param classroom 
 * @param major 
 * @param student 
 */


data class DomainsStudentMajorClassroom (

    @SerializedName("classroom")
    val classroom: Classroom,

    @SerializedName("major")
    val major: Major,

    @SerializedName("student")
    val student: DomainsStudent

) {


}

