/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param createdAt 
 * @param generalAttendanceId 
 * @param id 
 * @param studentId 
 */


data class DomainsGeneralAttendanceRecord (

    @SerializedName("created_at")
    val createdAt: kotlin.String,

    @SerializedName("general_attendance_id")
    val generalAttendanceId: kotlin.Int,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("student_id")
    val studentId: kotlin.Int

) {


}

