/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param deviceId 
 * @param id 
 * @param refreshToken 
 * @param studentId 
 * @param ttl 
 */


data class DomainsStudentToken (

    @SerializedName("device_id")
    val deviceId: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("refresh_token")
    val refreshToken: kotlin.String,

    @SerializedName("student_id")
    val studentId: kotlin.Int,

    @SerializedName("ttl")
    val ttl: kotlin.String

) {


}

