/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param schoolId 
 */


data class DomainsSubject (

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("school_id")
    val schoolId: kotlin.Int

) {


}

