/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param id 
 * @param name 
 * @param password 
 * @param role 
 * @param schoolId 
 */


data class DomainsUser (

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("password")
    val password: kotlin.String,

    @SerializedName("role")
    val role: kotlin.String,

    @SerializedName("school_id")
    val schoolId: kotlin.Int

) {


}

