/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.ConstantsAttendanceStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 * @param generalAttendanceId 
 * @param id 
 * @param status 
 * @param studentId 
 */


data class DomainsGeneralAttendanceRecord (

    @SerializedName("date_time")
    val dateTime: kotlin.String,

    @SerializedName("general_attendance_id")
    val generalAttendanceId: kotlin.Int,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("status")
    val status: ConstantsAttendanceStatus,

    @SerializedName("student_id")
    val studentId: kotlin.Int

) {


}

