/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.ModelsAttendanceStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attendanceId 
 * @param id 
 * @param note 
 * @param status 
 * @param studentId 
 */


data class DtoAttendanceStudent (

    @SerializedName("attendance_id")
    val attendanceId: kotlin.Int,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("note")
    val note: kotlin.String,

    @SerializedName("status")
    val status: ModelsAttendanceStatus,

    @SerializedName("student_id")
    val studentId: kotlin.Int

) {


}

