/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DomainsBatch

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param batch 
 * @param classroomsCount 
 * @param majorsCount 
 */


data class DtoBatchInfo (

    @SerializedName("batch")
    val batch: DomainsBatch,

    @SerializedName("classrooms_count")
    val classroomsCount: kotlin.Int,

    @SerializedName("majors_count")
    val majorsCount: kotlin.Int

) {


}

