/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param classroomId 
 * @param id 
 * @param name 
 * @param nis 
 */


data class DtoStudent (

    @SerializedName("classroom_id")
    val classroomId: kotlin.Int,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("nis")
    val nis: kotlin.String

) {


}

