/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DomainsStudent
import com.rizalanggoro.presensigo.openapi.models.DomainsStudentToken

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param student 
 * @param studentToken 
 */


data class DtoStudentAccount (

    @SerializedName("student")
    val student: DomainsStudent,

    @SerializedName("student_token")
    val studentToken: DomainsStudentToken

) {


}

