/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Subject
import com.rizalanggoro.presensigo.openapi.models.SubjectAttendance

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subject 
 * @param subjectAttendance 
 */


data class GetAllSubjectAttendancesItem (

    @SerializedName("subject")
    val subject: Subject,

    @SerializedName("subject_attendance")
    val subjectAttendance: SubjectAttendance

) {


}

