/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DtoAttendance
import com.rizalanggoro.presensigo.openapi.models.GetAttendanceItemRes

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attendance 
 * @param items 
 */


data class GetAttendanceRes (

    @SerializedName("attendance")
    val attendance: DtoAttendance,

    @SerializedName("items")
    val items: kotlin.collections.List<GetAttendanceItemRes>

) {


}

