/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Classroom

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param classroom 
 * @param studentCount 
 */


data class GetAllClassroomsByMajorIdItem (

    @SerializedName("classroom")
    val classroom: Classroom,

    @SerializedName("student_count")
    val studentCount: kotlin.Int

) {


}

