/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DtoAttendanceStudent
import com.rizalanggoro.presensigo.openapi.models.DtoStudent

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attendanceStudent 
 * @param student 
 */


data class GetAttendanceItemRes (

    @SerializedName("attendanceStudent")
    val attendanceStudent: DtoAttendanceStudent,

    @SerializedName("student")
    val student: DtoStudent

) {


}

