/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.GeneralAttendance
import com.rizalanggoro.presensigo.openapi.models.User

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param creator 
 * @param generalAttendance 
 */


data class GetAllGeneralAttendancesItem (

    @SerializedName("creator")
    val creator: User,

    @SerializedName("general_attendance")
    val generalAttendance: GeneralAttendance

) {


}

