/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Batch

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param batch 
 * @param majorCount 
 */


data class GetAllBatchesItem (

    @SerializedName("batch")
    val batch: Batch,

    @SerializedName("major_count")
    val majorCount: kotlin.Int

) {


}

