/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DtoAttendance

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attendances 
 */


data class GetAllAttendancesRes (

    @SerializedName("attendances")
    val attendances: kotlin.collections.List<DtoAttendance>

) {


}

