/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.CombinedStudentMajorClassroom
import com.rizalanggoro.presensigo.openapi.models.DtoLateness

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param items 
 * @param lateness 
 */


data class GetLatenessRes (

    @SerializedName("items")
    val items: kotlin.collections.List<CombinedStudentMajorClassroom>,

    @SerializedName("lateness")
    val lateness: DtoLateness

) {


}

