/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Batch
import com.rizalanggoro.presensigo.openapi.models.Classroom
import com.rizalanggoro.presensigo.openapi.models.Major
import com.rizalanggoro.presensigo.openapi.models.School
import com.rizalanggoro.presensigo.openapi.models.Student

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param batch 
 * @param classroom 
 * @param major 
 * @param school 
 * @param student 
 */


data class GetProfileStudentRes (

    @SerializedName("batch")
    val batch: Batch,

    @SerializedName("classroom")
    val classroom: Classroom,

    @SerializedName("major")
    val major: Major,

    @SerializedName("school")
    val school: School,

    @SerializedName("student")
    val student: Student

) {


}

