/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param deviceId 
 * @param nis 
 * @param schoolCode 
 */


data class LoginStudentReq (

    @SerializedName("device_id")
    val deviceId: kotlin.String,

    @SerializedName("nis")
    val nis: kotlin.String,

    @SerializedName("school_code")
    val schoolCode: kotlin.String

) {


}

