/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * Values: AttendancePresent,AttendancePermission,AttendanceSick,AttendanceAlpha
 */

enum class ModelsAttendanceStatus(val value: kotlin.String) {

    @SerializedName(value = "hadir")
    AttendancePresent("hadir"),

    @SerializedName(value = "izin")
    AttendancePermission("izin"),

    @SerializedName(value = "sakit")
    AttendanceSick("sakit"),

    @SerializedName(value = "alpha")
    AttendanceAlpha("alpha");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ModelsAttendanceStatus) "$data" else null

        /**
         * Returns a valid [ModelsAttendanceStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ModelsAttendanceStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

