/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 */


data class RefreshTokenStudentRes (

    @SerializedName("access_token")
    val accessToken: kotlin.String,

    @SerializedName("refresh_token")
    val refreshToken: kotlin.String

) {


}

