/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param endDate 
 * @param startDate 
 */


data class RequestsExportGeneralAttendance (

    @SerializedName("end_date")
    val endDate: kotlin.String,

    @SerializedName("start_date")
    val startDate: kotlin.String

) {


}

