/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param datetime 
 * @param note 
 */


data class RequestsCreateGeneralAttendance (

    @SerializedName("datetime")
    val datetime: kotlin.String? = null,

    @SerializedName("note")
    val note: kotlin.String? = null

) {


}

