/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.Major

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param majors 
 */


data class ResponsesGetAllMajorsByBatchId (

    @SerializedName("majors")
    val majors: kotlin.collections.List<Major>

) {


}

