/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DtoBatchInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param batches 
 */


data class ResponsesGetAllBatches (

    @SerializedName("batches")
    val batches: kotlin.collections.List<DtoBatchInfo>

) {


}

