/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DomainsGeneralAttendanceRecord

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param generalAttendanceRecord 
 */


data class ResponsesCreateGeneralAttendanceRecord (

    @SerializedName("general_attendance_record")
    val generalAttendanceRecord: DomainsGeneralAttendanceRecord

) {


}

