/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DomainsSubjectAttendance

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param subjectAttendance 
 */


data class ResponsesGetSubjectAttendance (

    @SerializedName("subject_attendance")
    val subjectAttendance: DomainsSubjectAttendance

) {


}

