/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.ResponsesClassroomMajor

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 */


data class ResponsesGetAllClassroomWithMajors (

    @SerializedName("data")
    val `data`: kotlin.collections.List<ResponsesClassroomMajor>

) {


}

