/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param file 
 * @param fileName 
 */


data class ResponsesExportGeneralAttendance (

    @SerializedName("file")
    val file: kotlin.String,

    @SerializedName("file_name")
    val fileName: kotlin.String

) {


}

