/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models

import com.rizalanggoro.presensigo.openapi.models.DomainsGeneralAttendance

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param generalAttendances 
 */


data class ResponsesGetAllGeneralAttendances (

    @SerializedName("general_attendances")
    val generalAttendances: kotlin.collections.List<DomainsGeneralAttendance>

) {


}

