/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.rizalanggoro.presensigo.openapi.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param classroomId 
 * @param code 
 * @param dateTime 
 * @param id 
 * @param note 
 * @param subjectId 
 */


data class SubjectAttendance (

    @SerializedName("classroom_id")
    val classroomId: kotlin.Int,

    @SerializedName("code")
    val code: kotlin.String,

    @SerializedName("date_time")
    val dateTime: kotlin.String,

    @SerializedName("id")
    val id: kotlin.Int,

    @SerializedName("note")
    val note: kotlin.String,

    @SerializedName("subject_id")
    val subjectId: kotlin.Int

) {


}

