name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Create .env for CI
      run: |
        echo "API_BASE_URL=\"https://api-presensigo.rizalanggoro.space\"" >> .env
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode signing key
      env:
        SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
      run: |
        mkdir -p android/app/
        echo $SIGNING_KEY_BASE64 | base64 --decode > android/app/release.jks
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: Get current date and commit hash
      id: date_and_hash
      run: |
        echo "date=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"
        echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Create Release using gh CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="build-${{ steps.date_and_hash.outputs.date }}-${{ steps.date_and_hash.outputs.hash }}"
        RELEASE_NAME="Continuous Integration Build"

        gh release create "$TAG_NAME" \
          --repo "$GITHUB_REPOSITORY" \
          --title "$RELEASE_NAME" \
          --notes "Automated release from commit ${{ github.sha }}" \
          --target "$GITHUB_SHA" \
          "app/build/outputs/apk/release/*.apk"
